spring:
  kafka:
    consumer:
      auto-offset-reset: earliest
  data.mongodb:
    host: mongo
    port: 27017

server:
  port: 9090
  
logging:
  level:
    org.springframework.data.mongodb.core.MongoTemplate: DEBUG

kafka:
  bootstrapAddress: kafka:9092
  groupId:
    key: groupId
    defaultValue: boot
  topic:
    name: menus
    boot: boot.t
    
consul:
  server: consul
  port: 8500
  
redis:
  server: redis
  port: 6379
  
spring.mail:
  subject: Weekly Menu
  from: weeklyMenu@recipes.com
  host: smtp.gmail.com
  port: 587
  username: *****
  password: *****
  properties.mail.smtp:
    auth: true
    starttls.enable: true
